name: Run ikabot

on:
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ endsWith(matrix.python-version, '-dev') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      if: "!endsWith(matrix.python-version, '-dev')"
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: deadsnakes/action@v1.0.0
      if: endsWith(matrix.python-version, '-dev')
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
    - name: Run unit tests
      run: |
        pip install pytest
        export PYTHONPATH="$PYTHONPATH;$(pwd)"
        pytest tests -vvvvvvvvvv
    - name: Just run ikabot
      run: |
        printf "\n\n" | python -m ikabot &> log.log || cat log.log
        grep "Failed to log in..." log.log && exit 0 || exit 1
