name: Build Artifacts

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: get-pip
      run: Invoke-WebRequest https://bootstrap.pypa.io/get-pip.py

    - name: Install PyInstaller
      run: python -m pip install PyInstaller

    - name: Install flask
      run: python -m pip install flask

    - name: Install ikabot
      run: python -m pip install ikabot

    - name: Build ikabot
      run: python -m PyInstaller --onedir ikabot/command_line.py

    - name: Rename
      run: |
        mv dist/command_line dist/ikabot
        mv dist/ikabot/command_line.exe dist/ikabot/ikabot.exe

    - name: Upload Pre-compiled Ikabot
      uses: actions/upload-artifact@v4
      with:
        name: PreCompiledIkabot
        path: "dist"